name: Publish Dotnet Packages To Nuget
on:
  push:
    branches: [ "master-dev" ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: push
      run: |
        git config --global user.email "mawenbo12@huawei.com"
        git config --global user.name "mawenbo"
        git branch
        git tag
        git for-each-ref refs/tags --sort=-taggerdate --format='%(refname)' --count=1
      shell: bash
