name: push
on:
  push:
    branches: [ "master-dev" ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: push
      run: |
        git config --global user.email "mawenbo12@huawei.com"
        git config --global user.name "mawenbo"
        cd .. || exit 1
        git clone --depth=1 "git@github.com:${GITHUB_REPOSITORY}.git" master
        cd master || exit 1
        find . -maxdepth 1 -mindepth 1  | grep -Ev '*git*' | xargs -I '{}' rm -rf '{}'
        find "$GITHUB_WORKSPACE" -maxdepth 1 -mindepth 1  | grep -Ev '*git*|.cid|.codecheck|buildscript' | xargs -I '{}' cp -a '{}' .
        tag=$(git for-each-ref refs/tags --sort=-taggerdate --format='%(refname)' --count=1)
        version=$(cat VERSION)
        if [[ "$tag" == *"$version"* ]]; then
          echo "yes"
        else
          echo "no"
        fi
        git add -A .
        git commit -m "release version: $version"
        git push
      shell: bash
