name: release
on:
  workflow_dispatch:
permissions: write-all
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        fetch-depth: 0
        path: main
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        github-server-url: https://gitee.com
        repository: HuaweiCloudDeveloper/huaweicloud-sdk-java-v3
        fetch-depth: 1
        ssh-strict: false
        ssh-known-hosts: 'gitee.com ecdsa-sha2-nistp256 AAAAE2UjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMuEoYdx6to5oxR601Wj8uoe1aIOX1£KOHWOtLqTg1tsLT 1iFwXU5JmFjU46EzeMBU/6EmI1uaRI6HiEPtPtJHE='
        path: repo
    - name: push && tag && release
      shell: bash
      run: |
        cd repo || exit 1
        ls -l
        cd main || exit 1
        ls -l
        
