name: release
on:
  workflow_dispatch:
permissions: write-all
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - name: Pull Source
      uses: actions/checkout@v3
      with:
        github-server-url: https://gitee.com
        repository: ${{ vars.SOURCE_REPO }}
        ssh-key: ${{ secrets.SSH_KEY }}
        ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}
        path: source
    - name: Pull Target
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        path: target
    - name: push && tag && release
      shell: bash
      run: |
        cd source || exit 1
        ls -l
        cd - || exit 1
        cd target || exit 1
        ls -l
        cd - || exit 1
        
