name: release
on:
  workflow_dispatch:
permissions: write-all
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        fetch-depth: 0
        ssh-strict: false
    - name: config
      run: |
        git lfs install
        git config --global http.postBuffer 1048576000
        git config --global core.compression 0
        git config user.name unionsdk
        git config user.email hwcloudsdk@huawei.com
    - name: push && tag && release
      shell: bash
      run: |
        # Pull the code from the source repository
        git clone --depth=1 $SOURCE repo
        cd repo || exit 1
        ls -a
      env:
        SOURCE: ${{ vars.SOURCE }}
        
