name: push
on:
  push:
    branches: [ "master-dev" ]
  workflow_dispatch:
permissions: write-all
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        fetch-depth: 0
    - name: config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: push
      shell: bash
      run: |
        version=$(cat VERSION)
        tag_name="v${version}"
        echo "version ${version} found on branch ${GITHUB_REF_NAME}" 
        mkdir ../temp || exit 1
        find . -maxdepth 1 -mindepth 1  | grep -Ev '*git*|.cid|.codecheck|buildscript' | xargs -I '{}' cp -a '{}' ../temp
        git checkout main
        find . -maxdepth 1 -mindepth 1  | grep -Ev '*git*' | xargs -I '{}' rm -rf '{}'
        mv ../temp/* .
        echo '-----BEGIN CONTENTS IN CURRENT DIR-----'
        ls -a
        echo '-----END CONTENTS IN CURRENT DIR-----'
        git add -A .
        if [[ "$(git status | grep 'nothing to commit')" ]]; then echo 'nothing to commit, exit' && exit 0; fi
        git commit -m "release version: $version"
        echo "git commit finished."
        git push origin main
        echo "git push finished."
        tag_exists=false
        for tag in $(git tag --list)
        do
          if [[ "$tag" == "$tag_name" ]]; then tag_exists=true && break; fi
        done
        if [[ "$tag_exists" == "false" ]]
        then
          commit_sha=$(git rev-parse HEAD)
          curl -L \
          -X POST \
          -H 'Accept: application/vnd.github+json' \
          -H 'content-type: application/json' \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          -d '{\"tag\":\"${tag_name}\",\"message\":\"\",\"object\":\"${commit_sha}\",\"type\":\"commit\"}' \
          https://api.github.com/repos/${{ github.repository }}/git/tags || exit 1
          echo "create tag ${tag_name} finished."
          curl -L \
          -X POST \
          -H 'Accept: application/vnd.github+json' \
          -H 'content-type: application/json' \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          -d "{\"tag_name\":\"${tag_name}\",\"name\":\"${tag_name}\",\"body\":\"Release ${version}\"}" \
          https://api.github.com/repos/${{ github.repository }}/releases || exit 1
          echo "create release ${version} finished."
        fi
