name: test
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: git push
      run: |
        current=$(date +%Y%m%d%H%m%s)
        echo "$current" > "$current"
        git add .
        git commit -m "$current"
        git push
