name: test
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ID_RSA: ${{ secrets.ID_RSA }}
        ID_RSA_PUB: ${{ secrets.ID_RSA_PUB }}
      env:
        GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL }}
        GIT_USER_NAME: ${{ vars.GIT_USER_NAME }} 
    - name: git config
      run: |
        git config --global user.email "$GIT_USER_EMAIL"
        git config --global user.name "$GIT_USER_NAME"
        if [ ! -d ~/.ssh ]
        then
            mkdir ~/.ssh
        fi
        echo "$ID_RSA" > ~/.ssh/id_rsa
        echo "ID_RSA_PUB > ~/.ssh/id_rsa.pub
    - name: git push
      run: |
        current=$(date +%Y%m%d%H%m%s)
        echo "$current" > "$current"
        git add .
        git commit -m "$current"
        git push
      shell: bash
