name: push
on:
  push:
    branches: [ "master-dev" ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        fetch-depth: 0
    - name: push
      run: |
        version=$(cat VERSION)
        mkdir ../temp || exit 1
        find . -maxdepth 1 -mindepth 1  | grep -Ev '*git*|.cid|.codecheck|buildscript' | xargs -I '{}' cp -a '{}' ../temp
        git checkout main
        find . -maxdepth 1 -mindepth 1  | grep -Ev '*git*' | xargs -I '{}' rm -rf '{}'
        mv ../temp/* .
        if [ -n "$(git tag --list)" ]; then tag=$(git describe --abbrev=0 --tags); fi
        if [[ "$tag" == *"$version"* ]]; then
          echo "yes"
        else
          echo "no"
        fi
        git add -A .
        git commit -m "release version: $version"
        git push
