name: push
on:
  push:
    branches: [ "master-dev" ]
  workflow_dispatch:
permissions: write-all
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        fetch-depth: 0
    - name: config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: push
      shell: bash
      run: |
        version=$(cat VERSION)
        tag_name="release/${version}"
        echo "version ${version} found on branch ${GITHUB_REF_NAME}" 
        mkdir ../temp || exit 1
        find . -maxdepth 1 -mindepth 1  | grep -Ev '*git*|.cid|.codecheck|buildscript' | xargs -I '{}' cp -a '{}' ../temp
        git checkout main
        find . -maxdepth 1 -mindepth 1  | grep -Ev '*git*' | xargs -I '{}' rm -rf '{}'
        mv ../temp/* .
        echo '-----BEGIN CONTENTS IN CURRENT DIR-----'
        ls -a
        echo '-----END CONTENTS IN CURRENT DIR-----'
        git add -A .
        if [[ "$(git status | grep 'nothing to commit')" ]]; then echo 'nothing to commit, exit' && exit 0; fi
        git commit -m "release version: $version"
        echo "git commit finished."
        tag_exists=false
        for tag in $(git tag --list)
        do
          if [[ "$tag" == "$tag_name" ]]; then tag_exists=true && break; fi
        done
        if [[ "$tag_exists" == "true" ]]
        then
          git push origin main
          echo "git push finished."
        else
          git tag -a "$tag_name" -m "" HEAD
          git push origin main "$tag_name"
          echo "git push tag ${tag_name} finished."
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/releases \
          --header 'content-type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --data "{\"tag_name\":\"v${version}\",\"target_commitish\":\"main\",\"name\":\"v${version}\",\"body\":\"Release ${version}\",\"draft\":false,\"prerelease\":false,\"generate_release_notes\":false}" || exit 1
          echo "git release ${version} finished."
        fi
